# #配置数据源
# spring:
#     datasource:
#         username: root
#         password: 2k3375^6o
#         url: jdbc:mysql://127.0.0.1:3306/se_disaster?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#         driver-class-name: com.mysql.cj.jdbc.Driver
# # 设置mp运行时行为
# mybatis-plus:
#     configuration:
#         log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt:
#     tokenHeader: Authorization
#     scret: yeb-secret
#     expiration: 14400
#     tokenHead: Bearer
